//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class credito
    {
        public int Id_tarjeta { get; set; }
        public Nullable<int> Numero_tarjeta { get; set; }
        public string Fecha_vencimiento { get; set; }
        public Nullable<int> cvc { get; set; }
        public Nullable<int> saldo { get; set; }
        public Nullable<int> deuda { get; set; }
    }
}
