//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class prestamo
    {
        public int Id_prestamo { get; set; }
        public Nullable<int> Saldo_prestado { get; set; }
        public Nullable<int> Saldo_pagado { get; set; }
        public Nullable<int> cuotas { get; set; }
    }
}
