//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int Id_Usuario { get; set; }
        public string Nombres { get; set; }
        public string Apellido { get; set; }
        public string Cedula { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public Nullable<int> Id_cuenta { get; set; }
        public Nullable<int> Id_tarjeta { get; set; }
        public Nullable<int> Id_credito { get; set; }
        public Nullable<int> Id_prestamo { get; set; }
        public string usuario1 { get; set; }
        public string clave { get; set; }
        public string Correo { get; set; }
        public string Codigo_Confirmacion { get; set; }
        public Nullable<byte> Confirmado { get; set; }
    }
}
