//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Entidad;
    
    public partial class BancoAPIEntities : DbContext
    {
        public BancoAPIEntities()
            : base("name=BancoAPIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrador> administradors { get; set; }
        public virtual DbSet<credito> creditoes { get; set; }
        public virtual DbSet<cuenta> cuentas { get; set; }
        public virtual DbSet<prestamo> prestamoes { get; set; }
        public virtual DbSet<tarjeta> tarjetas { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
